#!/usr/bin/env python3
"""Compatibility CLI for Quality Gate Baseline."""

from quality_gate_lib import (
    DEFAULT_CONFIG,
    FUNCTION_PATTERNS,
    PATTERN_EXTENSIONS,
    Finding,
    GateResult,
    analyze_documentation,
    analyze_documentation_file,
    build_llm_documentation_context,
    call_llm,
    calculate_score,
    count_file_lines,
    deep_get,
    find_functions,
    iter_documentation_files,
    iter_source_files,
    load_quality_gate_config,
    load_yaml_or_fallback,
    merge_config,
    markdown_headings,
    normalize_params,
    parse_cobertura_or_jacoco,
    parse_lcov,
    print_console_summary,
    read_coverage,
    resolve_report_paths,
    run_llm_documentation,
    run_quality_gate,
    should_exclude_dir,
    should_exclude_file,
    write_reports,
)
from quality_gate_lib.cli import main

__all__ = [
    "DEFAULT_CONFIG",
    "FUNCTION_PATTERNS",
    "PATTERN_EXTENSIONS",
    "Finding",
    "GateResult",
    "analyze_documentation",
    "analyze_documentation_file",
    "build_llm_documentation_context",
    "call_llm",
    "calculate_score",
    "count_file_lines",
    "deep_get",
    "find_functions",
    "iter_documentation_files",
    "iter_source_files",
    "load_quality_gate_config",
    "load_yaml_or_fallback",
    "main",
    "merge_config",
    "markdown_headings",
    "normalize_params",
    "parse_cobertura_or_jacoco",
    "parse_lcov",
    "print_console_summary",
    "read_coverage",
    "resolve_report_paths",
    "run_llm_documentation",
    "run_quality_gate",
    "should_exclude_dir",
    "should_exclude_file",
    "write_reports",
]


if __name__ == "__main__":
    raise SystemExit(main())
